# Generated by Django 6.0.6 on 2026-09-29 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_role_alter_user_role_userrolehistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSubjectRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject_id_snapshot",
                    models.PositiveBigIntegerField(
                        verbose_name="ID субъекта на момент запроса"
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("export", "Экспорт персональных данных")],
                        default="export",
                        max_length=20,
                        verbose_name="Тип запроса",
                    ),
                ),
                (
                    "http_method",
                    models.CharField(max_length=4, verbose_name="HTTP-метод"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("completed", "Выполнен")],
                        default="completed",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата запроса"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(verbose_name="Дата выполнения"),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="personal_data_request_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Субъект персональных данных",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запрос субъекта персональных данных",
                "verbose_name_plural": "Запросы субъектов персональных данных",
                "db_table": "data_subject_request_logs",
                "ordering": ["-requested_at"],
            },
        ),
    ]
